version: "3.8"

services:
  db:
    image: postgres:15
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty1234
        POSTGRES_DB: books
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data


  app:
    image: backend_book
    ports:
      - "14000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:qwerty1234@db/books
    depends_on:
      - db
volumes:
  postgres_data: